---
- name: Create Azure Infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Including Azure role for infrastructure creation
      include_role:
        name: azure
        tasks_from: azure_env_setup.yml
